Repository JeriRov/SB-BankingApp, pull requests merged in 2022-11, with the labels that each got.

#24 validation/MBA-40_create-fields-validation
  README.md
  src/main/java/com/ipz/mba/controllers/LoginController.java
  src/main/java/com/ipz/mba/validation/Validation.java
Labels: documentation, enhancement

#25 hotfix/MBA-42_fix-registration
  README.md
  src/main/java/com/ipz/mba/controllers/RegistrationsController.java
  src/main/java/com/ipz/mba/exceptions/ClientDataRegistrationValidationException.java
  src/main/java/com/ipz/mba/models/ClientDataRegistration.java
  src/main/java/com/ipz/mba/services/impl/RegistrationServiceImpl.java
Labels: documentation, enhancement, help wanted

#28 cardcreation/MBA-60_add-create-card-controller
  src/main/java/com/ipz/mba/controllers/NewCardController.java
  src/main/java/com/ipz/mba/models/NewCardData.java
  src/main/java/com/ipz/mba/repositories/CardTypeRepository.java
  src/main/java/com/ipz/mba/repositories/CustomerRepository.java
  src/main/java/com/ipz/mba/services/CardService.java
  src/main/java/com/ipz/mba/services/impl/CardServiceImpl.java
  src/main/java/com/ipz/mba/utils/CardGenerator.java
  src/main/java/com/ipz/mba/utils/Validation.java
Labels: enhancement

#29 refreshToken/MBA-57_provide-refresh-token
  README.md
  src/main/java/com/ipz/mba/controllers/LoginController.java
  src/main/java/com/ipz/mba/controllers/RefreshController.java
  src/main/java/com/ipz/mba/controllers/RegistrationsController.java
  src/main/java/com/ipz/mba/entities/UserEntity.java
  src/main/java/com/ipz/mba/filter/JWTFilter.java
  src/main/java/com/ipz/mba/models/ClientDataRegistration.java
  src/main/java/com/ipz/mba/models/RefreshToken.java
  src/main/java/com/ipz/mba/repositories/UserRepository.java
  src/main/java/com/ipz/mba/security/SecurityConfig.java
  src/main/java/com/ipz/mba/security/jwt/JWTUtil.java
  src/main/java/com/ipz/mba/services/RefreshTokenService.java
  src/main/java/com/ipz/mba/services/RegistrationService.java
  src/main/java/com/ipz/mba/services/impl/RefreshTokenServiceImpl.java
  src/main/java/com/ipz/mba/services/impl/RegistrationServiceImpl.java
Labels: enhancement, help wanted

#30 cardProvider/MBA-64_create-card-provider
  src/main/java/com/ipz/mba/entities/CardEntity.java
  src/main/java/com/ipz/mba/entities/ProviderEntity.java
Labels: enhancement, help wanted

#31 fixcreating/MBA-67_sync-newcardcontroller-with-front-end
  src/main/java/com/ipz/mba/controllers/CardsController.java
  src/main/java/com/ipz/mba/controllers/NewCardController.java
  src/main/java/com/ipz/mba/models/NewCardData.java
  src/main/java/com/ipz/mba/repositories/CardTypeRepository.java
  src/main/java/com/ipz/mba/repositories/ProviderRepository.java
  src/main/java/com/ipz/mba/services/CardService.java
  src/main/java/com/ipz/mba/services/impl/CardServiceImpl.java
  src/main/java/com/ipz/mba/utils/CardGenerator.java
  src/main/java/com/ipz/mba/utils/Validation.java
Labels: refactor

#32 expireDate/MBA-65_return-expire-date-with-refresh-&-access-tokens
  README.md
  src/main/java/com/ipz/mba/controllers/LoginController.java
  src/main/java/com/ipz/mba/controllers/RefreshController.java
  src/main/java/com/ipz/mba/controllers/RegistrationsController.java
  src/main/java/com/ipz/mba/security/jwt/JWTUtil.java
Labels: documentation, enhancement, help wanted

#33 transactionsController/MBA-72_controller-for-transactions
  README.md
  src/main/java/com/ipz/mba/controllers/CardsController.java
  src/main/java/com/ipz/mba/controllers/TransactionsController.java
Labels: documentation, enhancement, help wanted

#34 recentTransactions/MBA-66_return-all-performed-transactions-for-user
  README.md
  src/main/java/com/ipz/mba/controllers/TransactionsController.java
  src/main/java/com/ipz/mba/models/RecentTransactionInfo.java
  src/main/java/com/ipz/mba/repositories/TransactionRepository.java
  src/main/java/com/ipz/mba/services/TransactionService.java
  src/main/java/com/ipz/mba/services/impl/TransactionServiceImpl.java
Labels: documentation, enhancement

#35 allcards/MBA-69_all-user-cards-end-point
  src/main/java/com/ipz/mba/controllers/CardsController.java
  src/main/java/com/ipz/mba/repositories/CardRepository.java
  src/main/java/com/ipz/mba/services/CardService.java
  src/main/java/com/ipz/mba/services/impl/CardServiceImpl.java
Labels: enhancement

#36 cardbynumber/MBA-70_card-by-number-end-point
  README.md
  src/main/java/com/ipz/mba/controllers/CardsController.java
  src/main/java/com/ipz/mba/services/CardService.java
  src/main/java/com/ipz/mba/services/impl/CardServiceImpl.java
Labels: documentation, enhancement

#38 userInfo/MBA-76_getting-user-info
  README.md
  src/main/java/com/ipz/mba/controllers/UsersController.java
  src/main/java/com/ipz/mba/filter/JWTFilter.java
  src/main/java/com/ipz/mba/models/UserInfo.java
Labels: documentation, enhancement

#39 hotfix/MBA-59_backend-refactoring
  README.md
  src/main/java/com/ipz/mba/controllers/CardsController.java
  src/main/java/com/ipz/mba/controllers/LoginController.java
  src/main/java/com/ipz/mba/controllers/RefreshController.java
  src/main/java/com/ipz/mba/controllers/RegistrationsController.java
  src/main/java/com/ipz/mba/controllers/TransactionsController.java
  src/main/java/com/ipz/mba/repositories/TransactionRepository.java
  src/main/java/com/ipz/mba/security/SecurityConfig.java
  src/main/java/com/ipz/mba/security/filter/JWTFilter.java
  src/main/java/com/ipz/mba/security/jwt/JWTUtil.java
  src/main/java/com/ipz/mba/services/impl/CardServiceImpl.java
  src/main/java/com/ipz/mba/services/impl/RegistrationServiceImpl.java
  src/main/java/com/ipz/mba/services/impl/TransactionServiceImpl.java
  src/main/java/com/ipz/mba/utils/CardGenerator.java
Labels: documentation, refactor

#40 changepin/MBA-81_change-card-pin-end-point
  README.md
  src/main/java/com/ipz/mba/controllers/CardsController.java
  src/main/java/com/ipz/mba/services/CardService.java
  src/main/java/com/ipz/mba/services/impl/CardServiceImpl.java
  src/main/java/com/ipz/mba/utils/CardGenerator.java
Labels: documentation, enhancement

#41 fixTransactions/MBA-83_fix-getting-transactions
  src/main/java/com/ipz/mba/entities/TransactionEntity.java
  src/main/java/com/ipz/mba/models/RecentTransactionInfo.java
  src/main/java/com/ipz/mba/services/impl/CardServiceImpl.java
  src/main/java/com/ipz/mba/services/impl/TransactionServiceImpl.java
Labels: help wanted

#42 sortTransactions/MBA-84_sort-transactions-by-profit
  src/main/java/com/ipz/mba/models/RecentTransactionInfo.java
  src/main/java/com/ipz/mba/services/impl/TransactionServiceImpl.java
Labels: enhancement

#43 hotfix/MBA-85 _Add-repository-to-backend-and-fix-provider-setter
  pom.xml
  src/main/java/com/ipz/mba/utils/CardGenerator.java
Labels: help wanted
