Repository JeriRov/SB-BankingApp, pull requests merged in 2022-10, with the labels that each got.

#2 initial/setup-git
  README.md
  src/main/java/com/ipz/mba/controllers/AccountController.java
  src/main/java/com/ipz/mba/models/Account.java
  src/main/java/com/ipz/mba/repositories/AccountRepository.java
  src/main/java/com/ipz/mba/services/AccountService.java
Labels: documentation

#4 database/MBA-12_configure-AWS-hosting
  pom.xml
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: enhancement

#5 registration/MBA-14_сreate-registration
  pom.xml
  src/main/java/com/ipz/mba/controllers/RegistrationsController.java
  src/main/java/com/ipz/mba/entities/CustomerEntity.java
  src/main/java/com/ipz/mba/entities/UserEntity.java
  src/main/java/com/ipz/mba/exceptions/ClientDataRegistrationHasNullFieldsException.java
  src/main/java/com/ipz/mba/exceptions/UserAlreadyExistsException.java
  src/main/java/com/ipz/mba/models/ClientDataRegistration.java
  src/main/java/com/ipz/mba/repositories/CustomerRepository.java
  src/main/java/com/ipz/mba/repositories/UserRepository.java
  src/main/java/com/ipz/mba/services/RegistrationService.java
  src/main/resources/application.properties
Labels: enhancement

#7 config/configure-application
  .gitignore
  src/main/java/com/ipz/mba/controllers/AccountController.java
  src/main/java/com/ipz/mba/models/Account.java
  src/main/java/com/ipz/mba/repositories/AccountRepository.java
  src/main/java/com/ipz/mba/services/AccountService.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: documentation

#8 login/MBA-16_create-login
  src/main/java/com/ipz/mba/controllers/LoginController.java
  src/main/java/com/ipz/mba/services/LoginService.java
Labels: enhancement

#10 token/MBA-5_json-web-token-(JWT)
  pom.xml
  src/main/java/com/ipz/mba/filter/AuthenticationFilter.java
  src/main/java/com/ipz/mba/security/SecurityConfig.java
  src/main/java/com/ipz/mba/security/jwt/JWTProvider.java
Labels: enhancement

#11 authentication/MBA-19_authentication
  src/main/java/com/ipz/mba/filter/AuthenticationFilter.java
  src/main/java/com/ipz/mba/security/SecurityConfig.java
  src/main/java/com/ipz/mba/security/jwt/JWTProvider.java
Labels: enhancement

#12 MBA-17_security
  src/main/java/com/ipz/mba/security/SecurityConfig.java
Labels: enhancement

#13 hotfix/MBA-23_fix-db-entities
  src/main/java/com/ipz/mba/entities/CustomerEntity.java
  src/main/java/com/ipz/mba/entities/RoleEntity.java
  src/main/java/com/ipz/mba/entities/UserEntity.java
  src/main/java/com/ipz/mba/models/ClientDataRegistration.java
Labels: help wanted

#14 hotfix/MBA-24_fix-for-repositories-&-services
  src/main/java/com/ipz/mba/controllers/LoginController.java
  src/main/java/com/ipz/mba/models/ClientDataRegistration.java
  src/main/java/com/ipz/mba/repositories/RoleRepository.java
  src/main/java/com/ipz/mba/repositories/UserRepository.java
  src/main/java/com/ipz/mba/services/CustomerService.java
  src/main/java/com/ipz/mba/services/LoginService.java
  src/main/java/com/ipz/mba/services/RegistrationService.java
Labels: help wanted

#15 customer-security/MBA-25_provide-security-for-customers
  src/main/java/com/ipz/mba/security/models/CustomerDetails.java
  src/main/java/com/ipz/mba/security/services/CustomerDetailsService.java
Labels: enhancement

#16 hotfix/MBA-26_fix-authentication-&-authorization
  src/main/java/com/ipz/mba/filter/AuthenticationFilter.java
  src/main/java/com/ipz/mba/filter/JWTFilter.java
  src/main/java/com/ipz/mba/security/SecurityConfig.java
  src/main/java/com/ipz/mba/security/jwt/JWTProvider.java
  src/main/java/com/ipz/mba/security/jwt/JWTUtil.java
Labels: enhancement, help wanted

#17 hotfix/MBA-27_fix-login-and-registration-controllers
  src/main/java/com/ipz/mba/controllers/LoginController.java
  src/main/java/com/ipz/mba/controllers/RegistrationsController.java
Labels: help wanted

#18 hotfix/MBA-28_make-login-controller-by-post-method
  src/main/java/com/ipz/mba/controllers/LoginController.java
  src/main/java/com/ipz/mba/models/ClientDataLogin.java
Labels: help wanted

#19 passwordEncoder/MBA-32_develop-passwordencoder
  src/main/java/com/ipz/mba/security/SecurityConfig.java
  src/main/java/com/ipz/mba/services/RegistrationService.java
Labels: enhancement

#20 refactor/MBA-29_code-refactoring
  .gitignore
  src/main/java/com/ipz/mba/controllers/LoginController.java
  src/main/java/com/ipz/mba/controllers/RegistrationsController.java
  src/main/java/com/ipz/mba/entities/CustomerEntity.java
  src/main/java/com/ipz/mba/entities/RoleEntity.java
  src/main/java/com/ipz/mba/entities/UserEntity.java
  src/main/java/com/ipz/mba/filter/JWTFilter.java
  src/main/java/com/ipz/mba/models/ClientDataLogin.java
  src/main/java/com/ipz/mba/models/ClientDataRegistration.java
  src/main/java/com/ipz/mba/repositories/UserRepository.java
  src/main/java/com/ipz/mba/security/SecurityConfig.java
  src/main/java/com/ipz/mba/security/models/CustomerDetails.java
  src/main/java/com/ipz/mba/services/LoginService.java
  src/main/java/com/ipz/mba/services/RegistrationService.java
  src/main/java/com/ipz/mba/services/impl/RegistrationServiceImpl.java
  src/main/resources/application-prod.properties
Labels: refactor

#21 documentation/MBA-35_create-documentation
  README.md
Labels: documentation

#22 dev/MBA_sprint-2
  .gitignore
  README.md
  pom.xml
  src/main/java/com/ipz/mba/controllers/LoginController.java
  src/main/java/com/ipz/mba/controllers/RegistrationsController.java
  src/main/java/com/ipz/mba/entities/CustomerEntity.java
  src/main/java/com/ipz/mba/entities/RoleEntity.java
  src/main/java/com/ipz/mba/entities/UserEntity.java
  src/main/java/com/ipz/mba/exceptions/ClientDataRegistrationHasNullFieldsException.java
  src/main/java/com/ipz/mba/exceptions/UserAlreadyExistsException.java
  src/main/java/com/ipz/mba/filter/JWTFilter.java
  src/main/java/com/ipz/mba/models/ClientDataLogin.java
  src/main/java/com/ipz/mba/models/ClientDataRegistration.java
  src/main/java/com/ipz/mba/repositories/CustomerRepository.java
  src/main/java/com/ipz/mba/repositories/RoleRepository.java
  src/main/java/com/ipz/mba/repositories/UserRepository.java
  src/main/java/com/ipz/mba/security/SecurityConfig.java
  src/main/java/com/ipz/mba/security/jwt/JWTUtil.java
  src/main/java/com/ipz/mba/security/models/CustomerDetails.java
  src/main/java/com/ipz/mba/security/services/CustomerDetailsService.java
  src/main/java/com/ipz/mba/services/RegistrationService.java
  src/main/java/com/ipz/mba/services/impl/RegistrationServiceImpl.java
  src/main/resources/application.properties
Labels: main

#23 transactions/MBA-36_develop-transactions
  README.md
  src/main/java/com/ipz/mba/controllers/CardsController.java
  src/main/java/com/ipz/mba/entities/CardEntity.java
  src/main/java/com/ipz/mba/entities/CardTypeEntity.java
  src/main/java/com/ipz/mba/entities/CurrencyEntity.java
  src/main/java/com/ipz/mba/entities/CustomerEntity.java
  src/main/java/com/ipz/mba/entities/TransactionEntity.java
  src/main/java/com/ipz/mba/exceptions/CardNotActiveException.java
  src/main/java/com/ipz/mba/exceptions/CardNotFoundException.java
  src/main/java/com/ipz/mba/exceptions/TransactionFailedException.java
  src/main/java/com/ipz/mba/filter/JWTFilter.java
  src/main/java/com/ipz/mba/models/ClientDataRegistration.java
  src/main/java/com/ipz/mba/models/TransferRequestData.java
  src/main/java/com/ipz/mba/repositories/CardRepository.java
  src/main/java/com/ipz/mba/repositories/CurrencyRepository.java
  src/main/java/com/ipz/mba/repositories/TransactionRepository.java
  src/main/java/com/ipz/mba/security/models/CustomerDetails.java
  src/main/java/com/ipz/mba/services/CardService.java
  src/main/java/com/ipz/mba/services/impl/CardServiceImpl.java
Labels: enhancement
